### ISSUE TITLE
Some jobs will be skipped in some cases

### ISSUE THREAD

**Issue by vatsal2210** [cfurst/CronJobManager#12]
I have added more than 20 schedules at different time and days. If multiple jobs are scheduled at the exactly the same time or different time, some might be skipped.

**Comment by cfurst** [comment]
Cannot reproduce

**Comment by cfurst** [comment]
And to be fair there are limitations to timing accuracy due to the way nodejs works.. if you have jobs that are scheduled at the same time and have a lot of other stuff going on as well, a function tied to a cron will be placed on the scheduler at the scheduled time, yet will not get executed until the scheduler gives it execution time. Thus, the time it is placed on the scheduler and the time it actually gets executed may not match which make it appear to be executing late.

This is a limitation of nodejs and not this module.
