### ISSUE TITLE
Get Job ID from multiple job

### ISSUE THREAD

**Issue by vatsal2210** [cfurst/CronJobManager#13]
I am running multiple jobs so how should I get each job ID which is execute callback function in a manager ?

`var cronJob1 = manager.add('1' , "*/3 * * * * *", function () {             
   logger.info('cron job completed every 3 sec ', cronJob1.id);
});`

Can I get crobJob1.id in console.log ? When job is completed or job is executed on that time I want that job /schedule ID. I have to execute my code further on the basis of that ID.

**Comment by cfurst** [comment]
Interesting question!
Unfortunately there is no way to do that right now. At it is, that would be tricky because `cronJob1` will most likely have more than one job. We would have to bind the object containing the job to the Function somehow. The idea was to get a job via the key, not the other way round. Although I could see how that feature would be useful.

**Comment by cfurst** [comment]
Will consider as a feature request.
